name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ${{ github.actor == 'dependabot[bot]' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Check
        run: make check

      - name: Build
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: amd64
        run: make build
